[workspace]
members = ["Enums/enums1","guessing_game","package","resturant","commoncollection/vectors","commoncollection/hashmap",
"error/panic",
"generics/generic",
"generics/traits",
"third-party-crates/packages",
"tests/adder",
"project1/minigrep"
,"closures"]